spring.datasource.url = jdbc:postgresql://localhost:5432/demo
spring.datasource.username = postgres
spring.datasource.password = Admin66@@55@@
spring.datasource.driver-class-name = org.postgresql.Driver